platform :ios, '13.0'
use_frameworks!

target 'ADCoordinator_Example' do
  pod 'ADCoordinator', :path => '../'
  pod 'SwiftLint', '~> 0.53'

  target 'ADCoordinator_Tests' do
    inherit! :search_paths
  end
end
