name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Bundle install
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler: "Gemfile.lock"
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Bundle install Example
      uses: ruby/setup-ruby@v1
      with:
        working-directory: ./Example
        ruby-version: '3.2.2'
        bundler: "Gemfile.lock"
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Pod install
      working-directory: ./Example
      run: bundle exec pod install
    - name: Build and test
      run: bundle exec fastlane ci_check
    - name: Pod lib lint
      run: bundle exec pod lib lint
