name: Publish release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler: "Gemfile.lock"
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Publish release
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_CI }}
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN_CI }}
      run: bundle exec fastlane publish_release
